//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergardenFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooked
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; } = DateTime.Now;
        public int Food_ID { get; set; }
        public double Quantity { get; set; }
        public double Price { get; set; }
        public int Unit_ID { get; set; }
        public int Category_ID { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Units Units { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
