//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergardenFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kids_eating
    {
        public int Id { get; set; }
        public int Quantity { get; set; }
        public int Category { get; set; }
        public Nullable<System.DateTime> Record_date { get; set; } = DateTime.Now;
    
        public virtual Categories Categories { get; set; }
    }
}
