//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindergardenFood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Level { get; set; }
    
        public virtual Security_levels Security_levels { get; set; }
    }
}
